-
# tasks file for deploy-kubernetes
- name: Initializing the kubernetes cluster on the master node...
  become: yes
  shell: kubeadm init --pod-network-cidr=10.244.0.0/16
  ignore_errors: yes

- name: Creating .kube directory
  file:
    path: "/home/{{ ansible_user }}/.kube"
    recurse: yes
    state: directory
    mode: 0755

- name: Configuring users cluster access
  become: yes
  copy:
    src: /etc/kubernetes/admin.conf
    dest: "/home/{{ ansible_user }}/.kube/config"
    remote_src: yes
    owner: "{{ ansible_user }}"
 
- name: Installing Pod network.... (Flannel)
  shell: |
    export KUBECONFIG=/home/{{ ansible_user }}/.kube/config
    kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml

