---
# tasks file for get-join-command
- name: Getting join command from the master node...
  shell: kubeadm token create --print-join-command
  register: _join_command
  when: inventory_hostname == groups['kubemaster'][0]
  
- name: Setting join command...
  set_fact:
    join_command: "{{ hostvars[groups['kubemaster'][0]]['_join_command']['stdout_lines'][0] }}"

- name: run join command on workers
  shell: |
    {{ join_command }} --node-name {{ inventory_hostname }}
  when: inventory_hostname in groups['kubeworkers']

